### Try catch

**Dernière mise à jour avril 2024**  
Bon travail !

Nous reviendrons sur ce concept plus tard, en particulier lorsque nous aborderons le code synchrone et asynchrone en JavaScript. Nous verrons également comment vous pouvez créer vous-même une erreur en utilisant `throw new Error("description here")`. Cela sera particulièrement utile dans la gestion des promesses et des appels à l'API `fetch`.

## Récapitulatif du chapitre

- Lorsqu'un appel de fonction risque d'échouer, il est recommandé de l'envelopper dans un bloc `try...catch`.
- Cela permet de gérer et de récupérer des erreurs, évitant ainsi que le programme ne plante complètement.
```

